#!/usr/bin/bash

export BRTOOL_PREFIX=$(dirname $(realpath $0))

export BRTOOL_SRC_PREFIX="$BRTOOL_PREFIX"/brtool-src
export BRTOOL_COMMAND_PREFIX="$BRTOOL_SRC_PREFIX"/command

export BRTOOL_BUILD_PREFIX="$BRTOOL_PREFIX"/build
export BRTOOL_DEPSTAT_RECORD="$BRTOOL_BUILD_PREFIX"/dependency.status

export BRTOOL_BUILD_TYPES='debug release'
export BRTOOL_TARGET_PLATFORMS='penguin window'

export BRTOOL_LIBSRC_PREFIX="$HOME"/Source
export BRTOOL_INSTALL_PREFIX="$HOME"/.local

export BRTOOL_TEST_DIRNAME=test
export BRTOOL_TEST_PREFIX="$BRTOOL_PREFIX"/"$BRTOOL_TEST_DIRNAME"

export BRTOOL_DOCS_PREFIX="$BRTOOL_PREFIX"/docs 

declare -A COMMANDS

for cmdname in $(ls "$BRTOOL_COMMAND_PREFIX")
do
	COMMANDS["$cmdname"]="$BRTOOL_COMMAND_PREFIX"/"$cmdname"
done

source "$BRTOOL_SRC_PREFIX"/util

command="${1:-build}"

if ! find_array_element "$command" "${COMMANDS[@]}"
then
	die "command '$command' not found, see ./brtool help"
	echo 1
fi

command "${COMMANDS[$command]}" ${*:2}