#!/usr/bin/bash

project_dir=$(cd $(dirname $0) &> /dev/null && pwd)

report_dir=$project_dir/report

if [[ $1 == clean ]]; then
	rm -rf $report_dir/*
	exit 0
fi

build_dir=$project_dir/build/coverage

if [ ! -d $build_dir ]; then
	echo "no coverage test found: $project_dir/build/coverage"
	exit 1
fi

# cleanup *.gcda
lcov --zerocounters -d $build_dir

mkdir -p $report_dir

coverage_init=$report_dir/coverage_init.info
coverage_test=$report_dir/coverage_test.info
coverage_final=$report_dir/coverage.info

# init zero coverage for every instrumented line
lcov --capture -q --initial --directory $build_dir \
--output-file $coverage_init

$build_dir/pk_test > /dev/null

# count coverage
lcov --capture -q --directory $build_dir \
--output-file $coverage_test

# merge result
lcov --add-tracefile $coverage_init \
--add-tracefile $coverage_test \
--output-file $coverage_final

lcov --remove $coverage_final '/usr/*' \
--output-file $coverage_final

genhtml $coverage_final --output-directory $report_dir/page