#!/usr/bin/bash

sqlcipher_dir=$HOME/Source/sqlcipher
install_prefix=$HOME/.local

cd $sqlcipher_dir

flags="--disable-tcl --enable-tempstore=yes --prefix=$install_prefix"
cflags="-I$install_prefix/include -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -Os"
ldflags="-L$install_prefix/lib64 -lcrypto"

# we need mksourceid
if [[ ! -f mksourceid || $TARGET_PLATFORM != 'window' ]]
then
	./configure $flags CFLAGS="'$cflags'" LDFLAGS="'$ldflags'"

	make
fi

if [[ $TARGET_PLATFORM == 'window' ]]
then
	flags+=" --host=x86_64-w64-mingw32 --with-crypto-lib=none config_TARGET_EXEEXT=.exe"
	ldflags+=" -lcrypt32 -lws2_32"

	./configure $flags CFLAGS="'$cflags'" LDFLAGS="'$ldflags'"

	make clean

	make
fi

if ! grep -qs 'header_install' 'Makefile'
then
	echo '
header_install: sqlite3.h sqlite3ext.h
	$(INSTALL) -d $(DESTDIR)$(includedir)
	$(INSTALL) -m 0644 sqlite3.h $(DESTDIR)$(includedir)
	$(INSTALL) -m 0644 $(TOP)/src/sqlite3ext.h $(DESTDIR)$(includedir)' >> Makefile
fi

if ! grep -qs 'pc_install' 'Makefile'
then
	echo '
pc_install: sqlcipher.pc
	$(INSTALL) -d $(DESTDIR)$(pkgconfigdir)
	$(INSTALL) -m 0644 sqlcipher.pc $(DESTDIR)$(pkgconfigdir)' >> Makefile
fi

# make lib_install
# make header_install
# make pc_install