#!/usr/bin/bash

project_dir="$(cd $(dirname $0) &> /dev/null && pwd)"

build_types=("debug" "test" "coverage" "penguin" "window")
build_type="${1:-debug}"
build_dir="$project_dir/build"

if [[ $build_type == "clean" ]]; then
	rm -rf $(printf "$build_dir/%s " "${build_types[@]}")
	exit 0
fi

if printf '%s\0' "${build_types[@]}" | grep -Fxqz -- $build_type; then
	build_dir+="/$build_type"
else
	echo "not a valid build type: $build_type"
	exit 1
fi

echo "found build type: $build_type"

build_target="pk"

if [[ $build_type == "test" || $build_type == "coverage" ]]; then
	build_target="pk_test"
fi

./tool/make_sqlcipher $build_type

cmake -B $build_dir -DCMAKE_BUILD_TYPE=${build_type^} -DINSTALL_PREFIX="$HOME/.local"

cmake --build $build_dir --target $build_target