#!/usr/bin/bash
# you should NEVER execute this file manually, or you may get unexpected side effects

type="${1:-build}"

case "$type" in
'build')
	for build_prefix in $(ls -F "$BUILD_PREFIX" | grep -oP '.*(?=/)')
	do
		build_prefix="$BUILD_PREFIX"/"$build_prefix"

		if [[ -s "$build_prefix"/Makefile ]]
		then
			cmake --build "$build_prefix" --target clean
		fi
	done
	;;
'coredump')
	rm -rf "$BRTOOL_PREFIX"/core.*
	;;
'draft')
	rm -rf "$BRTOOL_PREFIX"/draft.*
	;;
*)
	die "cannot found '$1' in: [build | coredump | draft]"
	;;
esac