#!/usr/bin/bash

type="${1:-build}"

case "$type" in
'build')
	for build_prefix in $(ls -F "$BRTOOL_BUILD_PREFIX" | grep -oP '.*(?=/)')
	do
		cd "$BRTOOL_BUILD_PREFIX"/"$build_prefix"

		if [[ -s Makefile ]]
		then
			make clean
		fi
	done
	;;
'depstat')
	> "$BRTOOL_DEPSTAT_RECORD"
	;;
'coredump')
	rm "$PROJECT_PREFIX"/core.*
	;;
'draft')
	rm "$PROJECT_PREFIX"/draft.*
	;;
*)
	die "cannot found '$type' in: [build | coredump | draft]"
	;;
esac