#!/usr/bin/bash

build_type=${1:-debug}

if ! find_scalar_word "$build_type" "$BRTOOL_BUILD_PROFILES"
then
	die "unknown build type: $build_type"
fi

executable=$(find $BRTOOL_BUILD_PREFIX -maxdepth 1 -type f -regextype posix-extended -regex ".*/$1/.+\.exe$")

if [[ -z "$executable" ]]
then
	echo 'nothing to be done'
	exit 0
fi

scp "$executable" $(get_remote_info username)@$(get_remote_info address):$(get_remote_info workdir)