#!/usr/bin/bash

build_type=${1:-debug}

if ! find_array_element "$build_type" "$BUILD_TYPES"
then
	die "unknown build type '$build_type' to run this suit"
fi

build_prefix="$TEST_PREFIX"/build

export PKBIN="$BUILD_PREFIX"/"$build_type"/pk
export TEST_BUILD_PREFIX="$build_prefix"
export SRC_PREFIX="$BRTOOL_PREFIX"/src
export TEST_SANDBOX_PREFIX="$TEST_PREFIX"/sandbox

if [[ ! -s "$PKBIN" ]]
then
	command "$BRTOOL_PREFIX"/brtool
fi

if ! cmake -B $build_prefix -DPK_Test=1 -DLIB_INSTALL_PREFIX=$INSTALL_PREFIX \
-DCMAKE_BUILD_TYPE=${build_type^} -DCMAKE_TARGET_PLATFORM=Penguin  > /dev/null
then
	die 'stop building'
fi

if ! cmake --build "$build_prefix" --parallel 25 > /dev/null
then
	die 'stop building'
fi

echo "entering $TEST_PREFIX"
cd $TEST_PREFIX

prove -j25 ./