#!/usr/bin/bash

build_type=${1:-debug}

if ! find_array_element "$build_type" "$BUILD_TYPES"
then
	die "unknown build type '$build_type' to run this suit"
fi

build_prefix="$TEST_PREFIX"/build

export BUILD_PREFIX="$build_prefix" # override BUILD_PREFIX
export PKBIN="$build_prefix"/pk
export TEST_BUILD_PREFIX="$build_prefix"
export SRC_PREFIX="$BRTOOL_PREFIX"/src
export TEST_SANDBOX_PREFIX="$TEST_PREFIX"/sandbox

load_project_info

if ! cmake -B $build_prefix -DPK_TEST=1 -DINSTALL_PREFIX=$INSTALL_PREFIX \
-DCMAKE_BUILD_TYPE=${build_type^} -DCMAKE_TARGET_PLATFORM=Penguin  > /dev/null
then
	die 'stop building'
fi

if ! cmake --build "$build_prefix" --parallel 25 > /dev/null
then
	die 'stop building'
fi

echo "entering $TEST_PREFIX"
cd $TEST_PREFIX

prove -j25 ./