#!/usr/bin/bash

build_type=${1:-debug}

if ! find_array_element "$build_type" "$BRTOOL_BUILD_TYPES"
then
	die "unknown build type '$build_type' to run this suit"
fi

build_prefix="$BRTOOL_TEST_PREFIX"/build

export BRTOOL_BUILD_PREFIX="$build_prefix" # override BRTOOL_BUILD_PREFIX
export PKBIN="$build_prefix"/pk
export TEST_BUILD_PREFIX="$build_prefix"
export SRC_PREFIX="$BRTOOL_PREFIX"/src
export TEST_TMP_PREFIX="$BRTOOL_TEST_PREFIX"/tmp
export PK_CRED_KY="$TEST_TMP_PREFIX"/key
export PK_CRED_DB="$TEST_TMP_PREFIX"/db

load_project_info

if ! cmake -B $build_prefix -DPK_TEST=1 -DINSTALL_PREFIX=$BRTOOL_INSTALL_PREFIX \
-DCMAKE_BUILD_TYPE=${build_type^} -DCMAKE_TARGET_PLATFORM=Penguin
then
	die 'stop building'
fi

if ! cmake --build "$build_prefix" --parallel 25
then
	die 'stop building'
fi

rm -rf "$TEST_TMP_PREFIX"/*

echo "entering $BRTOOL_TEST_PREFIX"
cd $BRTOOL_TEST_PREFIX
echo
echo "################################STARTTEST################################"
echo

prove -j25 ./

rm -rf "$TEST_TMP_PREFIX"/*