#!/usr/bin/bash

skip_matched_depstat 'openssl'

prepare_extsrc 'openssl' 'git://git.openssl.org/openssl.git'

source "$BRTOOL_SOURCE_PREFIX"/uihandle

feature='no-apps no-shared no-deprecated no-stdio'
options="--prefix=$LIBRARY_INSTALL_PREFIX"

if [[ $PROGRAM_HOST == 'window' ]]
then
	target=mingw64
	options+=' --cross-compile-prefix=x86_64-w64-mingw32-'
fi

if [[ -s Makefile ]]
then
	process_start 'cleanup built files'
	process_exec 'rm -r ./*'
	process_end
fi

process_start "configuring openssl for $PROGRAM_HOST"
process_exec "../Configure $target $feature $options CFLAGS='-w'"
process_end


process_start 'building openssl'
process_exec 'make -j25'
process_end

process_start 'installing openssl'
process_exec 'make install_sw'
process_end

update_depstat_record 'openssl'