#!/usr/bin/bash
# you should NEVER execute this file manually, or you may get unexpected side effects

target_platform="$1"

if [[ -z "$target_platform" ]]
then
	die 'target platform not found'
fi

if depstat_match_prev 'sqlcipher' "$target_platform"
then
	exit 0
fi

cd $SOURCE_PREFIX

sqlcipher_src="$SOURCE_PREFIX"/sqlcipher

if [[ ! -d $sqlcipher_src ]]
then
	git clone 'https://github.com/sqlcipher/sqlcipher.git'
fi

cd $sqlcipher_src

flags="--disable-tcl --enable-tempstore=yes --prefix="$INSTALL_PREFIX""
cflags="-I"$INSTALL_PREFIX"/include -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -w -O3 -DNDEBUG"
ldflags="-L"$INSTALL_PREFIX"/lib64 -lcrypto"

source "$BRTOOL_SRC_PREFIX"/uihandle

# we need mksourceid for build windows executable
if [[ ! -s "$sqlcipher_src"/mksourceid || $target_platform != 'window' ]]
then
	process_start 'configuring sqlcipher for penguin'
	process_exec "./configure $flags CFLAGS='$cflags' LDFLAGS='$ldflags'"
	process_end

	process_start 'building sqlcipher for penguin'
	process_exec 'make -j25'
	process_end
fi

if [[ $target_platform == 'window' ]]
then
	flags+=" --host=x86_64-w64-mingw32 --with-crypto-lib=none config_TARGET_EXEEXT=.exe"
	ldflags+=" -lcrypt32 -lws2_32"

	process_start 'configuring sqlcipher for windows'
	process_exec "./configure $flags CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\""
	process_end

	# remove penguin build but keep mksourceid
	make clean > /dev/null

	process_start 'building sqlcipher'
	process_exec 'make -j25'
	process_end
fi

if ! grep -qs 'uninstall' 'Makefile'
then
	echo '
uninstall:
	rm -f $(DESTDIR)$(libdir)/libsqlcipher.la
	rm -f $(DESTDIR)$(bindir)/sqlcipher$(TEXE)
	rm -f $(DESTDIR)$(includedir)/sqlite3.h
	rm -f $(DESTDIR)$(includedir)/sqlite3ext.h
	rm -f $(DESTDIR)$(pkgconfigdir)/sqlcipher.pc' >> Makefile
fi

if ! grep -qs 'header_install' 'Makefile'
then
	echo '
header_install: sqlite3.h sqlite3ext.h
	$(INSTALL) -d $(DESTDIR)$(includedir)
	$(INSTALL) -m 0644 sqlite3.h $(DESTDIR)$(includedir)
	$(INSTALL) -m 0644 $(TOP)/src/sqlite3ext.h $(DESTDIR)$(includedir)' >> Makefile
fi

if ! grep -qs 'pc_install' 'Makefile'
then
	echo '
pc_install: sqlcipher.pc
	$(INSTALL) -d $(DESTDIR)$(pkgconfigdir)
	$(INSTALL) -m 0644 sqlcipher.pc $(DESTDIR)$(pkgconfigdir)' >> Makefile
fi

process_start 'installing sqlcipher'
process_exec 'make lib_install'
process_exec 'make header_install'
process_exec 'make pc_install'
process_end

update_depstat_record 'sqlcipher' "$target_platform"
process_cleanup