#!/usr/bin/bash

die()
{
	echo "$*" >&2
	exit 1
}

export -f die

find_array_element()
{
	for el in "$2"
	do
		if [[ "$el" == "$1" ]]
		then
			return 1
		fi
	done

	return 0
}

export -f find_array_element

get_pair_value()
{
	grep -oP "^$1=.+" "$2" | cut -d '=' -f2
}

export -f get_pair_value

get_remote_info()
{
	get_pair_value "$1" "$BRTOOL_PREFIX"/remote.info
}

export -f get_remote_info

if [[ ! -s "$BRTOOL_PREFIX"/remote.info ]]
then
	die "$BRTOOL_PREFIX/remote.info: file not exists"
fi

get_project_info()
{
	get_pair_value "$1" "$BRTOOL_PREFIX"/project.info
}

export -f get_project_info

if [[ ! -s "$BRTOOL_PREFIX"/project.info ]]
then
	die "$BRTOOL_PREFIX/project.info: file not exists"
fi

load_project_info()
{
	export ARCHITECTURE=$(uname -m)
	export BUILD_COMMIT=$(git rev-parse HEAD)

	export PK_VERSION=$(get_project_info version)
	export PK_AUTHOR=$(get_project_info author)
	export PK_AUTHOR_CONTACT=$(get_project_info contact)
	export PK_PROJNAME=$(get_project_info projname)
	export PK_LICENSE_NOTIES=$(get_project_info license_noties)
}

export -f load_project_info