#!/usr/bin/bash
# depstat stands for dependency status

depstat_match_prev()
{
	if [[ -s "$BRTOOL_DEPSTAT_RECORD" && "$(get_pair_value "$1" "$BRTOOL_DEPSTAT_RECORD")" == "$2" ]]
	then
		return 0
	else
		return 1
	fi
}

skip_matched_depstat()
{
	if depstat_match_prev "$1" "$PROGRAM_HOST"
	then
		echo "skipped building $1"
		exit 0
	fi
}

export -f depstat_match_prev skip_matched_depstat

update_depstat_record()
{
	if [[ ! -s "$BRTOOL_DEPSTAT_RECORD" ]]
	then
		mkdir -p $(dirname "$BRTOOL_DEPSTAT_RECORD")
		touch "$BRTOOL_DEPSTAT_RECORD"
	fi

	if [[ -z "$(get_pair_value "$1" "$BRTOOL_DEPSTAT_RECORD")" ]]
	then
		echo "$1"=""$PROGRAM_HOST"" >> "$BRTOOL_DEPSTAT_RECORD"
	else
		sed -i "s/^\($1=\).*/\1"$PROGRAM_HOST"/" "$BRTOOL_DEPSTAT_RECORD"
	fi
}

export -f update_depstat_record
