#!/usr/bin/bash

project_root="$(cd $(dirname $0) &> /dev/null && pwd)/.."

source "$project_root/tool/util"

check_depstat 'sqlcipher'

cd $source_dir

sqlcipher_dir="$source_dir/sqlcipher"

if [[ ! -d $sqlcipher_dir ]]
then
	git clone 'https://github.com/sqlcipher/sqlcipher.git'
fi

cd $sqlcipher_dir

flags="--disable-tcl --enable-tempstore=yes --prefix=$install_prefix"
cflags="-I$install_prefix/include -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -Os"
ldflags="-L$install_prefix/lib64 -lcrypto"

# we need mksourceid
if [[ ! -f mksourceid || $TARGET_PLATFORM != 'window' ]]
then
	process_start 'configuring sqlcipher for penguin'
	process_exec "./configure $flags CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\""
	process_end

	process_start 'building sqlcipher for penguin'
	process_exec 'make -j25'
	process_end
fi

if [[ $TARGET_PLATFORM == 'window' ]]
then
	flags+=" --host=x86_64-w64-mingw32 --with-crypto-lib=none config_TARGET_EXEEXT=.exe"
	ldflags+=" -lcrypt32 -lws2_32"

	process_start 'configuring sqlcipher for windows'
	process_exec "./configure $flags CFLAGS=\"$cflags\" LDFLAGS=\"$ldflags\""
	process_end

	# remove penguin build but keep mksourceid
	make clean > /dev/null

	process_start 'building sqlcipher'
	process_exec 'make -j25'
	process_end
fi

if ! grep -qs 'uninstall' 'Makefile'
then
	echo '
uninstall:
	rm -f $(DESTDIR)$(libdir)/libsqlcipher.la
	rm -f $(DESTDIR)$(bindir)/sqlcipher$(TEXE)
	rm -f $(DESTDIR)$(includedir)/sqlite3.h
	rm -f $(DESTDIR)$(includedir)/sqlite3ext.h
	rm -f $(DESTDIR)$(pkgconfigdir)/sqlcipher.pc' >> Makefile
fi

if ! grep -qs 'header_install' 'Makefile'
then
	echo '
header_install: sqlite3.h sqlite3ext.h
	$(INSTALL) -d $(DESTDIR)$(includedir)
	$(INSTALL) -m 0644 sqlite3.h $(DESTDIR)$(includedir)
	$(INSTALL) -m 0644 $(TOP)/src/sqlite3ext.h $(DESTDIR)$(includedir)' >> Makefile
fi

if ! grep -qs 'pc_install' 'Makefile'
then
	echo '
pc_install: sqlcipher.pc
	$(INSTALL) -d $(DESTDIR)$(pkgconfigdir)
	$(INSTALL) -m 0644 sqlcipher.pc $(DESTDIR)$(pkgconfigdir)' >> Makefile
fi

process_start 'installing sqlcipher'
process_exec 'make lib_install'
process_exec 'make header_install'
process_exec 'make pc_install'
process_end

process_cleanup
set_depstat 'sqlcipher'