#!/usr/bin/bash

project_root="$(cd $(dirname $0) &> /dev/null && pwd)/.."

source "$project_root/tool/util"

check_depstat 'openssl'

openssl_dir="$source_dir/openssl"

cd $source_dir

if [[ ! -d $openssl_dir ]]
then
	git clone 'git://git.openssl.org/openssl.git'
fi

cd $openssl_dir

target='linux-x86_64'
flag="--prefix=$install_prefix"
feature='no-apps no-shared no-docs no-tests no-legacy '\
'no-threads no-ssl no-ssl-trace no-thread-pool no-stdio '\
'no-ui-console no-engine no-sock no-uplink no-deprecated '\
'no-dynamic-engine'

if [[ $target_platform == 'window' ]]
then
	target=mingw64
	flag+=' --cross-compile-prefix=x86_64-w64-mingw32-'
fi

if [[ -f 'Makefile' ]]
then
	process_start 'cleanup build files'
	process_exec 'make clean'
	process_end
fi

process_start "configuring openssl for $target_platform"
process_exec "./Configure $target $feature $flag CFLAGS=-Os"
process_end

process_start 'building openssl'
process_exec 'make -j25' # Cores Plus One
process_end

process_start 'installing openssl'
process_exec 'make install_sw'
process_end

process_cleanup
set_depstat 'openssl'