#!/usr/bin/bash

current_time()
{
	date +%s%N | cut -b1-13
}

spinner()
{
	local spin='-\|/'
	local i=0

	while kill -0 "$1" 2>/dev/null
	do
		i=$(( (i + 1) % 4 ))
		printf '%s\b' "${spin:$i:1}"
		sleep .2
	done
}

process_start()
{
	printf -- '-- %s... ' "$*"
}

process_exec()
{
	process_exec_starts_at=$(current_time)

	eval $* > "$LIBRARY_BUILD_LOG" 2>&1 &
	local cmd_pid=$!

	spinner "$cmd_pid"

	wait "$cmd_pid"

	return $?
}

process_end()
{
	local rescode=$?

	if [[ $rescode != 0 ]]
	then
		echo "no (result: $rescode)"
		echo "log generated at $LIBRARY_BUILD_LOG"
		exit $rescode
	else
		elapsed_time="$(bc <<< "scale=1; ($(current_time) - $process_exec_starts_at) / 1000")"
		printf "ok (%.1fs)\n" "$elapsed_time"
	fi
}
