= pk-init(1)

== NAME

pk-init - Initialize database for storing user credentials

== SYNOPSIS

[verse]
pk init [--encrypt[=<key>]] [--[no-]remember] [<options>]

== DESCRIPTION

This command will generate a db file (and an optional key file). By default,
their pathnames are obtained from the environment variables PK_CRED_DB and
PK_CRED_KY. If their environment variables are not defined in the current
session, for example, PK_CRED_DB is not defined, then this db file will be
created in the current working directory ($ pwd). The default names for the db
file and key file are '.pk-credfl' and '.pk-credky'.

A key file will be generated if one of the following conditions is met:

* Encrypt db using Raw Key Data and --no-remember option is NOT present
* Encrypt db using Passphrase and --remember option is present

== KEY FILE

The key file stores the most important things: the key and related cipher
configurations.

IMPORTANT: The database can be successfully decrypted ONLY IF the cipher
configurations are the same as those used the first time (initial phase) the
database was opened. Thus, please DO NOT LOSE this key file if you have one,
and store it in a safe location.

== KEY FORMAT

Key can take one of the following forms

* Passphrase with Key Derivation
* Raw Key Data (Without Key Derivation)
* Raw Key Data with Explicit Salt (Without Key Derivation)

For more information about keys and how to pass them, see
<https://www.zetetic.net/sqlcipher/sqlcipher-api/#PRAGMA_key>

== OPTIONS

--encrypt[=<key>]::
	Encrypt database with key. The key can be a Passphrase (With Key
	Derivation), Raw Key Data (Without Key Derivation), or Raw Key Data
	with Explicit Salt (Without Key Derivation).
+
Without `key` specified, the key will be Raw Key Data generated by *pk*. If the
environment variable 'PK_CRED_KY' exists, this key will be stored in the file
that PK_CRED_KY points to. Otherwise, it will be stored in the current working
directory, with a default name of '.pk-credky'.

--[no-]remember::
	Remember controls whether to store the key. When using Raw Key Data as a
	key, this option is set to TRUE by default. When using a Passphrase as a
	key, it is set to FALSE by default.

--kdf-algorithm::
	KDF algorithm used to generate the encryption key for the database. This
	option has no effect when using raw key data (without key derivation).
	The default value is PBKDF2_HMAC_SHA512, however PBKDF2HMAC_SHA256, and
	PBKDF2_HMAC_SHA1 are also supported.

--hmac-algorithm::
	HMAC algorithm used to detect illegal data tampering. The default value
	is HMAC_SHA512, however HMAC_SHA256, and HMAC_SHA1 are also supported.

--cipher-compat::
	Setting this option and passing in 1, 2, 3, or 4 will cause operations
	to be performed using the default settings consistent with the current
	database version number. The default value is 4.

--page-size::
	page_size can be used to adjust the page size for the encrypted database.
	The value for page_size must be a power of two between 512 and 65536
	inclusive. The default page size is 4096 bytes.

--kdf-iter::
	The PBKDF2 key derivation used to strengthen the key and make it
	resistent tobrute force and dictionary attacks. The default
	configuration uses 256,000 PBKDF2 iterations (effectively 512,000 SHA512
	operations).

== NOTE

The '--kdf-algorithm' and '--kdf-iter' options only take effect if the key is
raw key data.

Reducing the number of iterations is not recommended if a passphrase is in use.

The following options only take effect when '--encrypt' option is specified

* --[no-]remember
* --kdf-algorithm
* --hmac-algorithm
* --cipher-compat
* --page-size
* --kdf-iter
