find_package(PkgConfig REQUIRED)

set(ENV{PKG_CONFIG_PATH} "${INSTALL_PREFIX}/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")

pkg_check_modules(SQLCIPHER REQUIRED sqlcipher)

if("${CMAKE_BUILD_TYPE}" STREQUAL Window)
	list(APPEND SQLCIPHER_LIBRARIES "crypto")
	list(APPEND SQLCIPHER_LIBRARIES "crypt32")
	list(APPEND SQLCIPHER_LIBRARIES "ws2_32")
	list(APPEND SQLCIPHER_LIBRARY_DIRS "${INSTALL_PREFIX}/lib64")
else()
	list(APPEND SQLCIPHER_LIBRARIES "crypto")
	list(APPEND SQLCIPHER_LIBRARIES "m")
endif()

mark_as_advanced(SQLCIPHER_INCLUDE_DIRS SQLCIPHER_LIBRARIES SQLCIPHER_LIBRARY_DIRS)