#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define PROJECT_VERSION	"${PassKeeper_VERSION_MAJOR}.${PassKeeper_VERSION_MINOR}.${PassKeeper_VERSION_PATCH}"

#define ARCHITECTURE	"$ENV{ARCHITECTURE}"
#define BUILD_COMMIT	"$ENV{BUILD_COMMIT}"

#define AUTHOR		"$ENV{AUTHOR}"
#define CONTACT		"$ENV{CONTACT}"
#define PROJNAME	"$ENV{PROJNAME}"
#define LICENSE_NOTIES	"$ENV{LICENSE_NOTIES}"

#define PK_CRED_DB	"$ENV{PK_CRED_DB}"
#define PK_CRED_KY	"$ENV{PK_CRED_KY}"

#endif /* PROJECT_CONFIG_H */